image: gradle:jdk11


before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle


test:
  stage: test
  artifacts:
    paths:
      - build/reports/jacoco/test/html
    reports:
      junit: build/test-results/test/TEST-*.xml
    expire_in: 1 week
  script:
    - gradle test jacocoTestReport
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle